### ISSUE TITLE
Cannot set property 'fromString' of undefined

### ISSUE THREAD

**Issue by jfelchner** [gdub22/ember-cli-inline-content#11]
We're trying to deploy to Heroku and for some reason we keep getting this error.  Everything builds into `dist` fine locally and runs locally.

```
BuildingBuilding.Build failed.
Cannot set property 'fromString' of undefined
TypeError: Cannot set property 'fromString' of undefined
```

We've tried clearing the Heroku cache but still nothing.

The only thing we're using `inlineContent` for is this:

```js
var app = new EmberApp({
  inlineContent: {
    'analytics' : {
      file: './analytics.js',
      postProcess: function(content) {
        return content.replace(/\{\{SEGMENT_KEY\}\}/g, config.segmentKey);
      }
    }
  }
});
```

it was working fine before we upgraded to `ember-cli 0.2.2`

The full stacktrace given to us by Heroku is as follows:

```
       TypeError: Cannot set property 'fromString' of undefined
           at InlineContentRenderer.renderScript (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli-inline-content/index.js:81:30)
           at InlineContentRenderer.contentFor (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli-inline-content/index.js:41:23)
           at /tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli/lib/broccoli/ember-app.js:1249:49
           at Array.reduce (native)
           at EmberApp.contentFor (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli/lib/broccoli/ember-app.js:1248:33)
           at replacement (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:68:36)
           at String.replace (native)
           at CustomReplace.processFile (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:72:25)
           at CustomReplace.process (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli/lib/broccoli/broccoli-config-replace.js:52:10)
           at lib$rsvp$$internal$$tryCatch (/tmp/build_cf0dd66cf1a6dce9411922de861dbcca/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
```

Thanks for taking the time to look at this!

**Comment by gdub22** [comment]
@jfelchner try updating this addon to the latest version (0.4.0). Looks like you are using an old version.  I see a method in the stack trace that has since been refactored out.

**Comment by jfelchner** [comment]
@gdub22 we fixed it by adding:

```js
minifyJS: {
  options: {}
}
```

to our `EmberApp` initializer.  I'll let you know if the new version works without it whenever we upgrade.

**Comment by gdub22** [comment]
Yea, definitely resolved in the latest version which removed directly minifying inline content in favor of a separate addon.
